/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LABORATORIO
 */
public class jfrmEditorTexto extends javax.swing.JFrame {

    /**
     * Creates new form jfrmEditorTexto
     */
    public jfrmEditorTexto() {
        initComponents();
        //tamaño
        this.setSize(500, 300);
        //centrar
        this.setLocationRelativeTo(null);
        //titulo
        this.setTitle("Editor de Texto");
        //dejar fijo el tamaño
        this.setResizable(false);
        //
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnuArchivo = new javax.swing.JMenu();
        jmItemSalir = new javax.swing.JMenu();
        jmnuEdicion = new javax.swing.JMenu();
        jmItemCortar = new javax.swing.JMenuItem();
        jmItemCopiar = new javax.swing.JMenuItem();
        jmItemPegar = new javax.swing.JMenuItem();
        jmnuOpciones = new javax.swing.JMenu();
        jmFuente = new javax.swing.JMenu();
        jmItemCourierNew = new javax.swing.JMenuItem();
        jmItemArial = new javax.swing.JMenuItem();
        jmItemPredeterminada = new javax.swing.JMenuItem();
        jmnuTam = new javax.swing.JMenu();
        jmItem16 = new javax.swing.JMenuItem();
        jmItem24 = new javax.swing.JMenuItem();
        jmItemPredeterminado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton2.setText("jButton2");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setText("jButton3");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jmnuArchivo.setText("Archivo");

        jmItemSalir.setMnemonic('s');
        jmItemSalir.setText("Salir");
        jmnuArchivo.add(jmItemSalir);

        jMenuBar1.add(jmnuArchivo);

        jmnuEdicion.setText("Edición");

        jmItemCortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmItemCortar.setMnemonic('c');
        jmItemCortar.setText("Cortar");
        jmItemCortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemCortarActionPerformed(evt);
            }
        });
        jmnuEdicion.add(jmItemCortar);

        jmItemCopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmItemCopiar.setMnemonic('c');
        jmItemCopiar.setText("Copiar");
        jmnuEdicion.add(jmItemCopiar);

        jmItemPegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmItemPegar.setMnemonic('p');
        jmItemPegar.setText("Pegar");
        jmnuEdicion.add(jmItemPegar);

        jMenuBar1.add(jmnuEdicion);

        jmnuOpciones.setText("Opciones");

        jmFuente.setMnemonic('f');
        jmFuente.setText("Fuente");

        jmItemCourierNew.setText("Courier New");
        jmFuente.add(jmItemCourierNew);

        jmItemArial.setText("Arial");
        jmFuente.add(jmItemArial);

        jmItemPredeterminada.setText("Predeterminado");
        jmFuente.add(jmItemPredeterminada);

        jmnuOpciones.add(jmFuente);

        jmnuTam.setMnemonic('t');
        jmnuTam.setText("Tamaño");

        jmItem16.setText("16");
        jmItem16.setToolTipText("");
        jmnuTam.add(jmItem16);

        jmItem24.setText("24");
        jmnuTam.add(jmItem24);

        jmItemPredeterminado.setText("Predeterminado");
        jmnuTam.add(jmItemPredeterminado);

        jmnuOpciones.add(jmnuTam);

        jMenuBar1.add(jmnuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 252, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmItemCortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemCortarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmItemCortarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmEditorTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmEditorTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmEditorTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmEditorTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmEditorTexto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu jmFuente;
    private javax.swing.JMenuItem jmItem16;
    private javax.swing.JMenuItem jmItem24;
    private javax.swing.JMenuItem jmItemArial;
    private javax.swing.JMenuItem jmItemCopiar;
    private javax.swing.JMenuItem jmItemCortar;
    private javax.swing.JMenuItem jmItemCourierNew;
    private javax.swing.JMenuItem jmItemPegar;
    private javax.swing.JMenuItem jmItemPredeterminada;
    private javax.swing.JMenuItem jmItemPredeterminado;
    private javax.swing.JMenu jmItemSalir;
    private javax.swing.JMenu jmnuArchivo;
    private javax.swing.JMenu jmnuEdicion;
    private javax.swing.JMenu jmnuOpciones;
    private javax.swing.JMenu jmnuTam;
    // End of variables declaration//GEN-END:variables
}
